apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: locust-script
  namespace: locust
data: 
  locustfile.py: |- 
    from locust import HttpUser, task, between 

    class QuickstartUser(HttpUser): 
        wait_time = between(0.7, 1.3) 

        @task(1) 
        def visit_website(self): 
            with self.client.get("/", headers={"Host": "argo.romiari.me", "User-Agent": "Mozilla"}, timeout=0.2, catch_response=True) as response: 
                if response.request_meta["response_time"] > 200: 
                    response.failure("request failed") 
                else: 
                    response.success() 
  
        @task(5) 
        def visit_website(self): 
            with self.client.get("/", headers={"Host": "romiari.me", "User-Agent": "Mozilla"}, timeout=0.2, catch_response=True) as response: 
                if response.request_meta["response_time"] > 200: 
                    response.failure("request failed") 
                else: 
                    response.success()