apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app-svm
  namespace: monitoring
  labels:
    prometheus: monitoring-kube
spec:
  endpoints:
  - port: http
    interval: 30s
  namespaceSelector:
    matchNames:
    - example-app
  selector:
    matchLabels:
      app: example-app