apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: simple-app
  namespace: monitoring
  labels:
    prometheus: monitoring-kube
spec:
  endpoints:
  - port: http
    interval: 30s
  namespaceSelector:
    matchNames:
    - simple-app
  selector:
    matchLabels:
      argocd.argoproj.io/instance: simple-app