apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: simple-app
  namespace: monitoring
  labels:
    app: simple-app
    prometheus: monitoring-kube
spec:
  endpoints:
  - interval: 30s
    port: 3000
  selector:
    matchLabels:
      app: simple-app