---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-locust
  namespace: argocd-romo
  # Remove k8s resources when argocd app is removed
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@gitlab.com:romi-ari/kube-lab-cd.git
    targetRevision: HEAD
    path: app/locust
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
